import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const { renderView } = require('../src/view');
const { Broker } = require('../src/broker');
const { chromium } = await import(process.env.MESH_PLAYWRIGHT_MODULE || 'playwright');
const root = new URL('../', import.meta.url);
const template = await readFile(new URL('media/index.html', root), 'utf8');
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = []; let searches = 0, fail = false, ready = false;
page.on('pageerror', error => errors.push(error.message));
const graph = { nodes: [{ id: 'mesh-fixture', label: 'Fixture decision', type: 'decision', tier0: true, community: 0, importance: 1, tags: ['mesh'] }, { id: 'related-fixture', label: 'Related note', type: 'note', community: 0, importance: .5, tags: ['mesh'] }], edges: [{ source: 'mesh-fixture', target: 'related-fixture', kind: 'related' }], communities: [{ id: 0, label: 'Fixture', color: '#7caaff', size: 2 }], vault: '/fixture' };
graph.meta = { vault: '/fixture', index_id: 'mesh-fixture', node_count: 2, edge_count: 1, max_orbit: 1 };
graph.nodes.forEach((node, index) => Object.assign(node, { path: node.id + '.md', line: 1, degree: 1, size: 1, orbit: index }));
const client = { async request(path) {
  if (fail) throw new Error('offline');
  let body;
  if (path === '/graph.json') body = graph;
  else if (path === '/api/status') body = { counts: { notes: 2, edges: 1 }, signals: {} };
  else if (path.startsWith('/api/search?')) { searches++; body = { cards: [{ NoteID: 'mesh-fixture', Title: 'Fixture decision', Type: 'decision', Snippet: 'Shared knowledge', Path: 'decisions/fixture.md' }], tokens: 20 }; }
  else if (path.startsWith('/api/note/')) body = { path: 'decisions/fixture.md', html: '<h1>Fixture decision body</h1><p>Safe shared knowledge.</p><a href="command:workbench.action.closeWindow">Unsafe command</a>' };
  else if (path === '/api/docs') body = { pages: [{ slug: 'intro', title: 'Introduction' }] };
  else if (path === '/api/docs/intro') body = { html: '<h1>Fixture documentation</h1>' };
  else if (path === '/api/dashboard') body = {};
  else assert.fail('Unexpected endpoint ' + path);
  return { status: 200, body: JSON.stringify(body) };
} };
let broker;
const reset = () => { broker?.dispose(); broker = new Broker(client, message => page.evaluate(data => window.dispatchEvent(new MessageEvent('message', { data })), message).catch(() => {}), { ready: () => { ready = true; } }); };
await page.exposeFunction('__meshMessage', message => broker.handle(message));
await page.addInitScript(() => { window.acquireVsCodeApi = () => ({ postMessage: message => window.__meshMessage(message), getState: () => null, setState: () => {} }); });
await page.route('**/*', async route => {
  const u = new URL(route.request().url());
  assert.equal(u.origin, 'https://mesh-ide.test', 'Renderer escaped local resources');
  if (u.pathname === '/') return route.fulfill({ contentType: 'text/html', body: renderView(template, { resource: p => u.origin + '/' + p, cspSource: u.origin }) });
  assert(/^\/(?:media\/(?:[a-z0-9]+\.(?:js|css)|fonts\/[a-z-]+\.woff2)|src\/(?:bridge\.js|view\.css))$/.test(u.pathname), 'Unapproved resource ' + u.pathname);
  return route.fulfill({ contentType: u.pathname.endsWith('.css') ? 'text/css' : u.pathname.endsWith('.woff2') ? 'font/woff2' : 'application/javascript', body: await readFile(new URL(u.pathname.slice(1), root)) });
});
try {
  reset(); await page.goto('https://mesh-ide.test/');
  await page.locator('#rail-status').filter({ hasText: '2 notes' }).waitFor(); assert(ready);
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#overlay').evaluate(el => el.classList.contains('hidden')), true, await page.locator('#overlay-msg').textContent());
  await page.locator('[data-view=search]').click(); await page.locator('#srch-q').fill('fixture');
  await page.waitForTimeout(500); assert.equal(searches, 0, 'Typing spent a retrieval call');
  await page.locator('#srch-q').press('Enter');
  await page.waitForTimeout(300);
  assert.equal(await page.locator('.rcard').count(), 1, await page.locator('#srch-results').textContent());
  await page.locator('.rcard').waitFor(); assert.equal(searches, 1);
  await page.locator('.rcard').click(); await page.getByText('Fixture decision body', { exact: true }).waitFor();
  const link = page.getByText('Unsafe command', { exact: true });
  assert.equal(await link.getAttribute('href'), null);
  const url = page.url(); await link.click(); await link.click({ button: 'middle' }); await link.click({ button: 'right' }); assert.equal(page.url(), url);
  await link.evaluate(el => el.setAttribute('href', 'vscode://file/tmp/not-allowed'));
  await page.waitForTimeout(20); assert.equal(await link.getAttribute('href'), null);
  await page.locator('[data-view=docs]').click(); await page.getByText('Fixture documentation', { exact: true }).waitFor();
  await page.locator('[data-view=graph]').click(); await page.locator('#browse').click();
  await page.locator('#explorer').filter({ has: page.locator('.exp-list') }).waitFor();
  await mkdir(new URL('test-results/', root), { recursive: true });
  await page.screenshot({ path: fileURLToPath(new URL('test-results/mesh-ide-wide.png', root)) });
  await page.setViewportSize({ width: 720, height: 850 });
  assert(parseFloat(await page.locator('[data-view=search]').evaluate(el => getComputedStyle(el).fontSize)) >= 12, 'Split-view navigation lost its labels');
  await page.locator('[data-view=search]').click();
  await page.screenshot({ path: fileURLToPath(new URL('test-results/mesh-ide-split.png', root)) });
  fail = true; await page.locator('#srch-q').fill('offline'); await page.locator('#srch-q').press('Enter');
  await page.getByText('Search failed:', { exact: false }).waitFor();
  fail = false; await page.locator('#srch-q').press('Enter'); await page.locator('.rcard').waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS Chromium graph, explicit search, note, docs, split layout, blocked command link and failure/recovery.');
} finally { broker?.dispose(); await browser.close(); }
